"""add activity_events and activity_actions tables

Revision ID: e636212b35b4
Revises: 1a2b3c4d5e6f
Create Date: 2026-09-29 20:49:28.146290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e636212b35b4'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events')),
    sa.UniqueConstraint('signal_id', name='uq_activity_events_signal_id'),
    sa.UniqueConstraint('source', 'entity_type', 'entity_id', 'event_time', 'content_hash', name='uq_activity_events_dedup')
    )
    # Use raw SQL for DESC indexes — autogenerate cannot emit functional index expressions.
    op.execute(
        "CREATE INDEX idx_activity_events_lookup "
        "ON activity_events (source, entity_type, entity_id, event_time DESC)"
    )
    op.create_table('activity_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_entity_type', sa.String(length=32), nullable=False),
    sa.Column('actor_entity_id', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('target_entity_type', sa.String(length=32), nullable=False),
    sa.Column('target_entity_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['activity_events.signal_id'], name=op.f('fk_activity_actions_signal_id_activity_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_actions'))
    )
    op.execute(
        "CREATE INDEX idx_activity_actions_actor "
        "ON activity_actions (source, actor_entity_type, actor_entity_id, event_time DESC)"
    )
    op.execute(
        "CREATE INDEX idx_activity_actions_target "
        "ON activity_actions (source, target_entity_type, target_entity_id, event_time DESC)"
    )
    op.alter_column('application_settings', 'importance',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('application_settings', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('catalog_metadata', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('graph_themes', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('graph_themes', 'source',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_graph_themes_default_per_base'), table_name='graph_themes', postgresql_where='is_default')
    op.drop_constraint(op.f('uq_graph_themes_name_base_theme'), 'graph_themes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_graph_themes_name_base_theme'), 'graph_themes', ['name', 'base_theme'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_graph_themes_default_per_base'), 'graph_themes', ['base_theme'], unique=True, postgresql_where='is_default')
    op.alter_column('graph_themes', 'source',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.alter_column('graph_themes', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('catalog_metadata', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('application_settings', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('application_settings', 'importance',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'optional'::character varying"),
               existing_nullable=False)
    op.execute("DROP INDEX IF EXISTS idx_activity_actions_target")
    op.execute("DROP INDEX IF EXISTS idx_activity_actions_actor")
    op.drop_table('activity_actions')
    op.execute("DROP INDEX IF EXISTS idx_activity_events_lookup")
    op.drop_table('activity_events')
    # ### end Alembic commands ###
