"""Abstract base class for LLM providers.

This module defines the interface that all LLM providers must implement
to integrate with the AI agent system.
"""

from abc import ABC, abstractmethod
from typing import Any, AsyncIterator, Dict, List, Optional


class LLMProvider(ABC):
    """Abstract base class for LLM providers.
    
    All LLM providers (OpenAI, Custom, etc.) must inherit from this class
    and implement its abstract methods to ensure compatibility with the
    AI agent system.
    
    The provider abstraction handles:
    - Chat completion requests
    - Token counting (native or estimated)
    - Model validation
    - Provider-specific configuration
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Return the provider name (e.g., 'openai', 'custom').
        
        Returns:
            Provider name as lowercase string
        """
    
    @property
    @abstractmethod
    def default_model(self) -> str:
        """Return the default model name for this provider.
        
        Returns:
            Default model identifier (e.g., 'gpt-3.5-turbo', 'gpt4')
        """
    
    @property
    @abstractmethod
    def supports_native_token_counting(self) -> bool:
        """Indicate if provider supports native token counting.
        
        Returns:
            True if provider has accurate token counting, False if estimation is used
        """
    
    @abstractmethod
    def chat_completion(
        self,
        messages: Optional[List[Dict[str, str]]] = None,
        model: Optional[str] = None,
        instructions: Optional[str] = None,
        input_text: Optional[str] = None,
        prompt_cache_key: Optional[str] = None,
        prompt_cache_retention: Optional[str] = None,
        max_output_tokens: Optional[int] = None,
    ) -> str:
        """Send a chat completion request and return the AI's response.
        
        This method handles the provider-specific API call to get a chat completion.
        It accepts either a standard `messages` list OR `instructions` and `input_text`
        for providers that support advanced features like the Responses API.
        
        Args:
            messages: Optional list of message dictionaries with 'role' and 'content' keys.
            model: Optional model name to use. If None, uses provider's default_model.
            instructions: Optional system instructions for the model.
            input_text: Optional user input text.
            prompt_cache_key: Optional key for prompt caching.
            prompt_cache_retention: Optional duration for caching (e.g., '24h').
            max_output_tokens: Optional maximum output tokens.
        
        Returns:
            The AI's response text as a string.
            
        Raises:
            RuntimeError: If the API call fails or returns an error.
            ValueError: If the model is not supported by this provider.
        """

    async def stream_chat_completion(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
    ) -> AsyncIterator[str]:
        """Async generator that streams chat completion tokens.

        This optional extension method enables providers to support streaming
        responses, yielding raw token strings as they are generated.

        Args:
            messages: List of message dictionaries with 'role' and 'content'.
            model: Optional model name to use.

        Yields:
            Token strings as they are generated by the provider.

        Raises:
            NotImplementedError: If the provider does not support streaming.
        """
        raise NotImplementedError(
            f"Provider '{self.name}' does not implement streaming chat completions"
        )
        # Make this an async generator by yielding from the base — unreachable but
        # satisfies Python's requirement that async generators contain at least one yield.
        yield  # type: ignore[unreachable]  # pragma: no cover

    def chat_completion_with_tools(
        self,
        messages: List[Dict[str, str]],
        tools: List[Dict[str, Any]],
        model: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Send a tool-enabled completion request.

        This optional extension method enables providers to support tool/function
        calling flows required by MCP orchestration, while preserving the existing
        plain-text chat_completion contract for backward compatibility.

        Args:
            messages: List of message dictionaries with 'role' and 'content'.
            tools: Provider-specific tool definitions.
            model: Optional model name to use.

        Returns:
            A provider-neutral structured payload with at least:
            - ``content``: Assistant text response (string)
            - ``tool_calls``: List of requested tool calls (list)
            - ``finish_reason``: Provider finish reason (string or None)

        Raises:
            NotImplementedError: If the provider does not support tool calling.
        """
        raise NotImplementedError(
            f"Provider '{self.name}' does not implement tool-enabled chat completions"
        )
    
    @abstractmethod
    def count_tokens(self, messages: List[Dict[str, str]], model: Optional[str] = None) -> int:
        """Count tokens in the message list.
        
        For providers with native token counting (like OpenAI with tiktoken),
        this should return accurate token counts. For others, it should return
        a reasonable estimation (e.g., character count ÷ 4).
        
        Args:
            messages: List of message dictionaries with 'role' and 'content' keys.
            model: Optional model name for model-specific encoding. If None, uses default.
        
        Returns:
            Total token count (actual or estimated) as an integer.
        """
    
    @abstractmethod
    def validate_model(self, model: str) -> bool:
        """Validate if a model name is supported by this provider.
        
        Args:
            model: Model identifier string to validate.
        
        Returns:
            True if the model is supported, False otherwise.
        """
    
    def _estimate_tokens_from_text(self, text: str) -> int:
        """Estimate token count from text using character-based approximation.
        
        This is a helper method for providers without native token counting.
        Uses a rough approximation of 1 token ≈ 4 characters.
        
        Args:
            text: Text content to estimate tokens for.
        
        Returns:
            Estimated token count.
        """
        return len(text) // 4
    
    def _estimate_tokens_from_messages(self, messages: List[Dict[str, str]]) -> int:
        """Estimate total tokens from a message list.
        
        Helper method that estimates tokens across all messages by summing
        character-based estimates for each message's content.
        
        Args:
            messages: List of message dictionaries.
        
        Returns:
            Estimated total token count.
        """
        total_chars = sum(len(msg.get("content", "")) for msg in messages)
        return total_chars // 4
