"""Unit tests for LangChain Neo4j chain path (read-only Cypher enforcement).

Tests the three-phase flow in ``query_neo4j_with_chain`` when
``FF_NEO4J_USE_PROVIDER_PIPELINE`` is ``False`` (the default):
generate Cypher via ``cypher_generation_chain``, validate with
``validate_read_only_query``, execute via ``execute_cypher_query``
(read-only session), then format via ``qa_chain``.
"""

from unittest.mock import MagicMock

import pytest

from app.ai_agent.chains import neo4j_chain
from app.settings import settings


pytestmark = pytest.mark.unit


class _FakeGraph:
    """Minimal Neo4j graph test double."""

    def __init__(self):
        self.schema = "(:Project)-[:HAS_ISSUE]->(:Issue)"

    def refresh_schema(self):
        return None


def _make_fake_chain(
    generated_cypher: str,
    qa_result: str | None = None,
) -> MagicMock:
    """Build a mock GraphCypherQAChain with controlled sub-runnables.

    Args:
        generated_cypher: The Cypher string that
            ``chain.cypher_generation_chain.invoke(...)`` should return.
        qa_result: The string that ``chain.qa_chain.invoke(...)`` should
            return. Defaults to ``"Formatted answer from QA chain."``.

    Returns:
        A MagicMock configured to look like a GraphCypherQAChain instance.
    """
    mock_chain = MagicMock()

    cypher_gen = MagicMock()
    cypher_gen.invoke.return_value = generated_cypher
    mock_chain.cypher_generation_chain = cypher_gen

    qa = MagicMock()
    qa.invoke.return_value = qa_result or "Formatted answer from QA chain."
    mock_chain.qa_chain = qa

    mock_chain.graph_schema = "(:Project)-[:HAS_ISSUE]->(:Issue)"

    return mock_chain


def test_langchain_path_rejects_write_cypher(monkeypatch):
    """Write Cypher generated by LangChain should be rejected before execution."""
    monkeypatch.setattr(settings, "FF_NEO4J_USE_PROVIDER_PIPELINE", False)
    monkeypatch.setattr(neo4j_chain, "get_neo4j_graph", lambda: _FakeGraph())

    mock_chain = _make_fake_chain("DETACH DELETE n")
    monkeypatch.setattr(
        neo4j_chain.GraphCypherQAChain, "from_llm", lambda **kw: mock_chain
    )

    # Spy on execute_cypher_query to ensure it is NOT called
    execute_spy = MagicMock()
    monkeypatch.setattr(neo4j_chain, "execute_cypher_query", execute_spy)

    provider = MagicMock()
    provider.name = "openai"

    result = neo4j_chain.query_neo4j_with_chain(
        "Delete everything", provider=provider
    )

    assert result is None
    execute_spy.assert_not_called()


def test_langchain_path_executes_read_cypher(monkeypatch):
    """Read-only Cypher generated by LangChain should be executed via safe path."""
    monkeypatch.setattr(settings, "FF_NEO4J_USE_PROVIDER_PIPELINE", False)
    monkeypatch.setattr(neo4j_chain, "get_neo4j_graph", lambda: _FakeGraph())

    mock_chain = _make_fake_chain(
        "MATCH (n) RETURN n LIMIT 5",
        "Found 5 nodes.",
    )
    monkeypatch.setattr(
        neo4j_chain.GraphCypherQAChain, "from_llm", lambda **kw: mock_chain
    )

    # validate_read_only_query must return True for read queries
    monkeypatch.setattr(neo4j_chain, "validate_read_only_query", lambda q: True)

    execute_spy = MagicMock(return_value=[{"n": {"name": "test"}}])
    monkeypatch.setattr(neo4j_chain, "execute_cypher_query", execute_spy)

    provider = MagicMock()
    provider.name = "openai"
    provider.default_model = "gpt-4"

    result = neo4j_chain.query_neo4j_with_chain("List nodes", provider=provider)

    assert result == "Found 5 nodes."
    execute_spy.assert_called_once()
    assert "MATCH (n) RETURN n LIMIT 5" in execute_spy.call_args[0][0]


def test_langchain_path_returns_none_for_empty_cypher(monkeypatch):
    """Empty Cypher from LangChain generation should return None."""
    monkeypatch.setattr(settings, "FF_NEO4J_USE_PROVIDER_PIPELINE", False)
    monkeypatch.setattr(neo4j_chain, "get_neo4j_graph", lambda: _FakeGraph())

    mock_chain = _make_fake_chain("")
    monkeypatch.setattr(
        neo4j_chain.GraphCypherQAChain, "from_llm", lambda **kw: mock_chain
    )

    execute_spy = MagicMock()
    monkeypatch.setattr(neo4j_chain, "execute_cypher_query", execute_spy)

    provider = MagicMock()
    provider.name = "openai"

    result = neo4j_chain.query_neo4j_with_chain("", provider=provider)

    assert result is None
    execute_spy.assert_not_called()