# pylint: disable=no-member

"""add connectors schema

Revision ID: 31c15cb26b13
Revises: c25f147d19c6
Create Date: 2026-03-15 20:49:24.014785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c15cb26b13'
down_revision: Union[str, Sequence[str], None] = 'c25f147d19c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.String(length=1023), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors')),
    sa.UniqueConstraint('connector_type', name=op.f('uq_connectors_connector_type'))
    )
    op.create_table('confluence_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('space_key', sa.String(length=255), nullable=False),
    sa.Column('space_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_confluence_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confluence_configs'))
    )
    op.create_table('email_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_email_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_configs'))
    )
    op.create_table('github_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1023), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('branch_name_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_github_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_configs')),
    sa.UniqueConstraint('connector_id', 'url', name=op.f('uq_github_configs_connector_id'))
    )
    op.create_table('google_docs_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.String(length=255), nullable=False),
    sa.Column('drive_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_google_docs_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_docs_configs'))
    )
    op.create_table('jira_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1023), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_api_token', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_jira_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_configs'))
    )
    op.create_table('sharepoint_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=1023), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_sharepoint_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sharepoint_configs'))
    )
    op.create_table('slack_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_slack_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slack_configs'))
    )
    op.create_table('teams_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_teams_configs_connector_id_connectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams_configs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams_configs')
    op.drop_table('slack_configs')
    op.drop_table('sharepoint_configs')
    op.drop_table('jira_configs')
    op.drop_table('google_docs_configs')
    op.drop_table('github_configs')
    op.drop_table('email_configs')
    op.drop_table('confluence_configs')
    op.drop_table('connectors')
    # ### end Alembic commands ###
